version: '3'
services:
  nginx: 
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80        
    restart: unless-stopped   
  ws-server:
    hostname: ws-server
    restart: unless-stopped
    ports:
      - 18080:8080
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    build:
      context: ./websocket-server
      dockerfile: Dockerfile